# Initial data source items have been asked to be refreshed,
# using top level categories rather than every 'numbered' item
# And adding to all existing data_sources
# Also adding category for #9879
namespace :data_source_items do
  desc 'Refresh Data Source Items'
  task refresh: :environment do
    # TODO: consider impact on existing demo projects
    puts 'ALL EXISTING DATA_SOURCE_ITEMS WILL BE REMOVED (AND FROM EXISTING PROJECTS)'
    cont = ask('CONTINUE? (yes/no): ')
    raise 'No action committed' unless cont.eql?('yes')
    remove_items_from_existing_projects
    DataSourceItem.destroy_all
    birth_data_sources = [DataSource.find_by_name('Births Gold Standard'),
                          DataSource.find_by_name('Birth Transaction')]
    birth_data_sources.each do |birth_source|
      birth_items.each_with_index do |birth_item, i|
        puts i
        DataSourceItem.create!(birth_item.merge(data_source_id: birth_source.id))
      end
    end
    death_data_sources = [DataSource.find_by_name('Deaths Gold Standard'),
                          DataSource.find_by_name('Death Transaction')]
    death_data_sources.each do |death_source|
      death_items.each do |death_item|
        DataSourceItem.create!(death_item.merge(data_source_id: death_source.id))
      end
    end

    # Further update
    DataSourceItem.where("category like '%Location%'").update_all(governance: 'DIRECT IDENTIFIER')
    DataSourceItem.where("name like '%ICD%'").update_all(governance: 'DIRECT IDENTIFIER')
  end

  private

  def remove_items_from_existing_projects
    Project.all.each do |project|
      next if project.data_source_items.empty?
      project.data_source_items = []
      project.save
    end
  end

  def birth_items
    [
      { name: 'MBISM204ID',
        description: "Unique identifier from ONS extract",
        occurrences: 1,
        category: "Record management_Identifier",
        governance: "NON IDENTIFYING DATA" },
      { name: 'LEDRM204ID',
        description: "LEDR identifier",
        occurrences: 1,
        category: "Record management_Identifier",
        governance: "NON IDENTIFYING DATA" },
      { name: 'BIRTHWGT',
        description: "Birth weight of child in grams",
        occurrences: 1,
        category: "Birth Event_Measurement",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CCGPOB',
        description: "Clinical Commissioning Group for place of birth of child",
        occurrences: 1,
        category: "Birth Event__LocationArea",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CESTRSS',
        description: "Communal Establishment code",
        occurrences: 1,
        category: "Birth Event__Location",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CTYPOB',
        description: "County code for place of birth of child",
        occurrences: 1,
        category: "Birth Event__LocationArea",
        governance: "NON IDENTIFYING DATA" },
      { name: 'DOBF',
        description: "Date of birth of father of child",
        occurrences: 1,
        category: "Third party Non-professional_Date",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'DOR',
        description: "Date of registration",
        occurrences: 1,
        category: "Registration_",
        governance: "NON IDENTIFYING DATA" },
      { name: 'ESTTYPEB',
        description: "Establishment type where birth occurred",
        occurrences: 1,
        category: "Birth Event__LocationType",
        governance: "NON IDENTIFYING DATA" },
      { name: 'HAUTPOB',
        description: "Health Authority code for place of birth of child",
        occurrences: 1,
        category: "Birth Event__LocationArea",
        governance: "NON IDENTIFYING DATA" },
      { name: 'HROPOB',
        description: "Health Regional Office code for place of birth of child",
        occurrences: 1,
        category: "Birth Event__LocationArea",
        governance: "NON IDENTIFYING DATA" },
      { name: 'LOAPOB',
        description: "Lowest Output Area for place of birth",
        occurrences: 1,
        category: "Birth Event__LocationArea",
        governance: "NON IDENTIFYING DATA" },
      { name: 'LSOAPOB',
        description: "Lower Super Output Area for place of birth",
        occurrences: 1,
        category: "Birth Event__LocationArea",
        governance: "NON IDENTIFYING DATA" },
      { name: 'MULTBTH',
        description: "Multiple Birth Indicator",
        occurrences: 1,
        category: "Birth Event_Multiple births",
        governance: "NON IDENTIFYING DATA" },
      { name: 'MULTTYPE',
        description: "Multiple birth type",
        occurrences: 1,
        category: "Birth Event_Multiple births",
        governance: "NON IDENTIFYING DATA" },
      { name: 'NHSIND',
        description: "NHS Establishment indicator",
        occurrences: 1,
        category: "Birth Event__Location",
        governance: "NON IDENTIFYING DATA" },
      { name: 'PCDPOB',
        description: "Postcode for place of birth of child",
        occurrences: 1,
        category: "Birth Event__Location",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'POBT',
        description: "Place of birth text",
        occurrences: 1,
        category: "Birth Event__Location",
        governance: "NON IDENTIFYING DATA" },
      { name: 'SBIND',
        description: "Stillbirth indicator",
        occurrences: 1,
        category: "Birth Event_Stillbirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'DOB',
        description: "Date of birth of child",
        occurrences: 1,
        category: "Birth Event__Date",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'FNAMCH1',
        description: "First forename of child",
        occurrences: 1,
        category: "ChildBorn_Name",
        governance: "DIRECT IDENTIFIER" },
      { name: 'FNAMCH2',
        description: "Second forename of child",
        occurrences: 1,
        category: "ChildBorn_Name",
        governance: "DIRECT IDENTIFIER" },
      { name: 'FNAMCH3',
        description: "Third forename of child",
        occurrences: 1,
        category: "ChildBorn_Name",
        governance: "DIRECT IDENTIFIER" },
      { name: 'FNAMCHX',
        description: "All Extra forenames of child are captured in this field",
        occurrences: 1,
        category: "ChildBorn_Name",
        governance: "DIRECT IDENTIFIER" },
      { name: 'GESTATN',
        description: "Gestation period (stillbirths only)",
        occurrences: 1,
        category: "Birth Event_Stillbirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'ICD9PV_ICD10PV',
        description: "ICD10 code Stillbirths only",
        occurrences: 20,
        category: "Birth Event_Stillbirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'ICD9PVF_ICD10PVF',
        description: "Final ICD10 code (still births only)",
        occurrences: 20,
        category: "Birth Event_Stillbirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'NHSNO',
        description: "NHS number of child",
        occurrences: 1,
        category: "ChildBorn_Identifier",
        governance: "DIRECT IDENTIFIER" },
      { name: 'SEX',
        description: "Coded sex of child",
        occurrences: 1,
        category: "ChildBorn_Sex",
        governance: "NON IDENTIFYING DATA" },
      { name: 'SNAMCH',
        description: "Surname of child",
        occurrences: 1,
        category: "ChildBorn_Name",
        governance: "DIRECT IDENTIFIER" },
      { name: 'COD10R',
        description: "Cause of stillbirth row position (Stillbirths only)",
        occurrences: 20,
        category: "Birth Event_Stillbirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CODFFT',
        description: "Cause of death free format  (Stillbirths only)",
        occurrences: 5,
        category: "Birth Event_Stillbirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'DEATHLAB',
        description: "Death during labour (stillbirths only)",
        occurrences: 1,
        category: "Birth Event_Stillbirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'WIGWO10',
        description: "ONS Hierarchical Classification of Stillbirth for ICD10 ",
        occurrences: 1,
        category: "Birth Event_Stillbirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'ADDRMT',
        description: "Usual address of Mother",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "DIRECT IDENTIFIER" },
      { name: 'AGEBF',
        description: "Age of father at birth of child",
        occurrences: 1,
        category: "Third party Non-professional_ParentAge",
        governance: "NON IDENTIFYING DATA" },
      { name: 'AGEBM',
        description: "Age of mother at birth of child",
        occurrences: 1,
        category: "Third party Non-professional_ParentAge",
        governance: "NON IDENTIFYING DATA" },
      { name: 'AGEMF',
        description: "Age of father at marriage to child's mother",
        occurrences: 1,
        category: "Third party Non-professional_ParentAge",
        governance: "NON IDENTIFYING DATA" },
      { name: 'AGEMM',
        description: "Age of mother at marriage to child's father",
        occurrences: 1,
        category: "Third party Non-professional_ParentAge",
        governance: "NON IDENTIFYING DATA" },
      { name: 'BTHIMAR',
        description: "Birth in marriage indicator",
        occurrences: 1,
        category: "Birth Event_MarriageStatus",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CCGRM',
        description: "Clinical Commissioning Group for usual residence of mother",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CTRYPOBF',
        description: "Country code of place of birth of father of child",
        occurrences: 1,
        category: "Third party Non-professional_ParentBirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CTRYPOBM',
        description: "Country code of place of birth of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_ParentBirth",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CTYDRM',
        description: "County district code of usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CTYRM',
        description: "County code of usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'DOBM',
        description: "Date of birth of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_Date",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'DURMAR',
        description: "Duration of marriage",
        occurrences: 1,
        category: "Birth Event_MarriageStatus",
        governance: "NON IDENTIFYING DATA" },
      { name: 'EMPSECF',
        description: "Employment status of father of child (SOC2000)",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: "NON IDENTIFYING DATA" },
      { name: 'EMPSECM',
        description: "Employment status of mother of child (SOC2000)",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: "NON IDENTIFYING DATA" },
      { name: 'EMPSTF',
        description: "Employment status of father of child (OCC90M)",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: "NON IDENTIFYING DATA" },
      { name: 'EMPSTM',
        description: "Employment status of mother of child (OCC90M)",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: "NON IDENTIFYING DATA" },
      { name: 'FNAMF',
        description: "First three Forename(s) of father/parent in this field",
        occurrences: 1,
        category: "Third party Non-professional_ParentName",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'FNAMFX',
        description: "Any Extra forename(s) of father/parent in this field",
        occurrences: 1,
        category: "Third party Non-professional_ParentName",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'FNAMM',
        description: "First three Forenames of mother in this field",
        occurrences: 1,
        category: "Third party Non-professional_ParentName",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'FNAMMX',
        description: "Any Extra forename(s) of mother in this field",
        occurrences: 1,
        category: "Third party Non-professional_ParentName",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'GORRM',
        description: "Government Office Region code of usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'HAUTRM',
        description: "Health Authority code for usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'HRORM',
        description: "Health Regional Office code for usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'LOARM',
        description: "Lowest Output Area for usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'LSOARM',
        description: "Lower Super Output Area for usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'NAMEMAID',
        description: "Mother's maiden name",
        occurrences: 1,
        category: "Third party Non-professional_ParentName",
        governance: "DIRECT IDENTIFIER" },
      { name: 'PCDRM',
        description: "Postcode of usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'SECCATF',
        description: "Socio-economic class of Father",
        occurrences: 1,
        category: "Third party Non-professional_Socio-economic",
        governance: "NON IDENTIFYING DATA" },
      { name: 'SECCATM',
        description: "Socio-economic class of Mother",
        occurrences: 1,
        category: "Third party Non-professional_Socio-economic",
        governance: "NON IDENTIFYING DATA" },
      { name: 'SNAMF',
        description: "Surname of father/parent",
        occurrences: 1,
        category: "Third party Non-professional_ParentName",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'SNAMM',
        description: "Surname of mother",
        occurrences: 1,
        category: "Third party Non-professional_ParentName",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'SNAMMCF',
        description: "Surname of mother at marriage to child's father/parent",
        occurrences: 1,
        category: "Third party Non-professional_ParentName",
        governance: "INDIRECT IDENTIFIER" },
      { name: 'SOC2KF',
        description: "Coded occupation (ONS Classification SOC2000 & SOC2010) for father of child",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: "NON IDENTIFYING DATA" },
      { name: 'SOC2KM',
        description: "Coded occupation (ONS Classification SOC2000 & SOC2010) for mother of child",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: "NON IDENTIFYING DATA" },
      { name: 'SOC90F',
        description: "Coded occupation (ONS Classification SOC1990) for father of child",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: "NON IDENTIFYING DATA" },
      { name: 'SOC90M',
        description: "Coded occupation (ONS Classification SOC1990) for mother of child",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: "NON IDENTIFYING DATA" },
      { name: 'STREGRM',
        description: "Standard region  code of usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'WARDRM',
        description: "Ward code of usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CCG9POB',
        description: "Clinical Commissioning Group for place of birth of child",
        occurrences: 1,
        category: "Birth Event__Location",
        governance: "NON IDENTIFYING DATA" },
      { name: 'CCG9RM',
        description: "Clinical Commissioning Group for usual residence of mother",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'GOR9RM',
        description: "Government Office Region code of usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" },
      { name: 'WARD9RM',
        description: "Ward code of usual residence of mother of child",
        occurrences: 1,
        category: "Third party Non-professional_MotherResidence",
        governance: "NON IDENTIFYING DATA" }
    ]
  end

  # TODO
  def death_items
    [
      { name: 'MBISID',
        description: "Unique identifier from ONS",
        occurrences: 1,
        category: "Record management_Identifier",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'LEDRID',
        description: "LEDR ID Unique identifier from LEDR Not available on M204",
        occurrences: 1,
        category: "Record management_Identifier",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CESTRSSR',
        description: "Communal establishment code of residence (If applicable",
        occurrences: 1,
        category: "Death Event__Location",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CESTSTAY',
        description: "Duration of stay in a Communal Establishment",
        occurrences: 1,
        category: "Care pre-death",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CCGPOD',
        description: "Clinical Commissioning Group for place of death",
        occurrences: 1,
        category: "Death event__LocationArea",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CESTRSS',
        description: "Communal establishment code RSS",
        occurrences: 1,
        category: "Death event_Location",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'COD10R',
        description: "Cause of death row position. CODROW pre ICD10",
        occurrences: 20,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'COD10RF',
        description: "Final cause of death row position. CODROW pre ICD10",
        occurrences: 20,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CODT',
        description: "Cause of death Text (only present if free format (CODFFT)  not present",
        occurrences: 5,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CTYDPOD',
        description: "County district for place of death",
        occurrences: 1,
        category: "Death event__LocationArea",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CTYPOD',
        description: "County code for place of death",
        occurrences: 1,
        category: "Death event__LocationArea",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'DESTER',
        description: "Destination if event occurred en route",
        occurrences: 1,
        category: "Death event__Location",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'DODDY',
        description: "Date of death day",
        occurrences: 1,
        category: "Death event__Date",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'DODMT',
        description: "Date of death month",
        occurrences: 1,
        category: "Death event__Date",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'DODYR',
        description: "Date of death year",
        occurrences: 1,
        category: "Death event__Date",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'ESTTYPED',
        description: "Establishment type where death occurred",
        occurrences: 1,
        category: "Death event__LocationType",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'HAUTPOD',
        description: "England: 1993-2002 strategic health authority for place of death, 2003- Primary Care Trust (PCT) for place of death. Wales: Health authority for place of death",
        occurrences: 1,
        category: "Death event__LocationArea",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'HROPOD',
        description: "England: 1993-2002 Health and social care directorate for place of death. 2003 - Strategic health authority for place of death. Wales: Health authority regional office for place of death",
        occurrences: 1,
        category: "Death event__LocationArea",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD9_ICD10',
        description: "ICD9 code pre 2000, International ICD10 code 2000 - 2013, IRIS ICD10 code 2014 onwards- non neonatal deaths only",
        occurrences: 20,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD9F_ICD10F',
        description: "ICD9 final code pre 2000, final international ICD10 code 2000 - 2013, IRIS ICD10PV code 2014 onwards - non neonatal deaths only",
        occurrences: 20,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD9PV_ICD10PV',
        description: "ICD9PV code pre 2000, International ICD10PV code 2000 - 2013, IRIS ICD10PV code 2014 onwards - neonatal deaths only",
        occurrences: 20,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD9PVF_ICD10PVF',
        description: "Final ICD9PV code pre 2000, final International ICD10PV code 2000 - 2013, final IRIS ICD10PV code 2014 onwards - neonatal deaths only",
        occurrences: 20,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD9SC_ICD10SC',
        description: "Secondary Cause code - ICD9 pre 2000, international ICD10 2000 - 2013, European(IRIS) code 2014 onwards- non neonatal deaths only",
        occurrences: 1,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD9SCF_ICD10SCF',
        description: "Final Secondary cause code -  ICD9 pre 2000, international ICD10 2000 - 2013, European(IRIS) code 2014 onwards- non neonatal deaths only",
        occurrences: 1,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD9U_ICD10U',
        description: "Underlying cause code - Underlying cause code - ICD9 pre 2000, international ICD10 2000 - 2013, European(IRIS) code 2014 onwards- non neonatal deaths only",
        occurrences: 1,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD9UF_ICD10UF',
        description: "Final Underlying cause code - ICD9 pre 2000, international ICD10 2000 - 2013, European(IRIS) code 2014- non neonatal deaths only",
        occurrences: 1,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD_FUTURE1',
        description: "One of two fields enabling future proofing for ICD coded outcomes",
        occurrences: 1,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ICD_FUTURE2',
        description: "One of two fields enabling future proofing for ICD coded outcomes",
        occurrences: 1,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'LINEN09_LNENO10',
        description: "Line number of cause text line for ICD10 code generated",
        occurrences: 20,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFIER DATA' },
      { name: 'LINENO9F_LNENO10F',
        description: "Final line number of cause text line for ICD cause code generated",
        occurrences: 20,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFIER DATA' },
      { name: 'LOAPOD',
        description: ",Lowest Output Area for place of death - - Currently not available, will be space filled",
        occurrences: 1,
        category: "Death event__Location",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'LSOAPOD',
        description: "Lower super area code for place of death - - Currently not available, will be space filled",
        occurrences: 1,
        category: "Death event__Location",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'NHSIND',
        description: "NHS Establishment Indicator",
        occurrences: 1,
        category: "Death event__LocationType",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'PCDPOD',
        description: "postcode of place of death of deceased",
        occurrences: 1,
        category: "Death event__Location",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'PLOACC9_PLOACC10',
        description: "Place of occurrence of Accident (if accidental death)",
        occurrences: 1,
        category: "Death event__Location",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'PODQUAL',
        description: "Place of death qualifier",
        occurrences: 1,
        category: "Death event__LocationType",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'PODT',
        description: "Place of Death text",
        occurrences: 1,
        category: "Death event__Location",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'WIGWO9_WIGWO10',
        description: "Wigglesworth code - although these fields are available, their content is presumed unsafe, therefore blanks will be output",
        occurrences: 1,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'WIGWO9F_WIGWO10F',
        description: "Final Wigglesworth code - although these fields are available, their content is presumed unsafe, therefore blanks will be output",
        occurrences: 1,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'ADDRDT',
        description: "Usual address of deceased",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'AGEC',
        description: "Calculated age of deceased",
        occurrences: 1,
        category: "Deceased_Age",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'AGECUNIT',
        description: "Units age stored in 1 Deceased_Age (1 = years, 2 = months, 3 = weeks, 4 = days < 7)",
        occurrences: 1,
        category: "OtherPossibleDataFields",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'AGEU1D',
        description: "Age of deceased if under 24hours",
        occurrences: 1,
        category: "DeceasedChild_Age",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'AKSNAMD',
        description: "Supplementary surnames of deceased",
        occurrences: 5,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'AKFNAMD1',
        description: "Supplementary first forenames of deceased",
        occurrences: 5,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'AKFNAMD2',
        description: "Supplementary second forenames of deceased",
        occurrences: 5,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'AKFNAMD3',
        description: "Supplementary third forenames of deceased",
        occurrences: 5,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'AKFND4I',
        description: "Supplementary fourth forename - Initials only of deceased",
        occurrences: 5,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'ALIASD',
        description: "Concatenated version of alias, also known as or even maiden names of deceased ",
        occurrences: 2,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'CCGR',
        description: "Clinical Commissioning Group of usual residence",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CTRYPOB',
        description: "Country code for place of birth of deceased",
        occurrences: 1,
        category: "Deceased_Birth",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CTRYR',
        description: "Country code for usual residence of deceased",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CTYDR',
        description: "County district code of usual residence of deceased",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CTYR',
        description: "County code of usual residence of deceased",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'DOBDY',
        description: "Date of birth day",
        occurrences: 1,
        category: "Deceased_Birth",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'DOBMT',
        description: "Date of birth month",
        occurrences: 1,
        category: "Deceased_Birth",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'DOBYR',
        description: "Date of birth year",
        occurrences: 1,
        category: "Deceased_Birth",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'FNAMD1',
        description: "First forename of deceased",
        occurrences: 1,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'FNAMD2',
        description: "Second forename of deceased",
        occurrences: 1,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'FNAMD3',
        description: "Third forename of deceased",
        occurrences: 1,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'FNAMDX',
        description: "Extra forenames of deceased",
        occurrences: 2,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'GORR',
        description: "Government office region code of usual residence of deceased",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'HAUTR',
        description: "England: 1993-2002 strategic health authority for place of residence of deceased, 2003- Primary Care Trust (PCT) for place of residence. Wales: Health authority for place of residence",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'HROR',
        description: "England: 1993-2002 Health and social care directorate for place of residence of deceased, 2003 - Strategic health authority for place of residence of deceased. Wales: Health authority regional office for place of residence",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'LOAR',
        description: "Lowest Output Area for usual residence of deceased - Currently not available, will be space filled",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'LSOAR',
        description: "Lower super area code for usual residence of deceased - (available 2013 onwards)",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'MARSTAT',
        description: "Marital status of the deceased",
        occurrences: 1,
        category: "Death Event_MarriageStatus",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'NAMEMAID',
        description: "Maiden name of deceased married woman",
        occurrences: 1,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'NHSNO',
        description: "NHSNO from NHSCR (or other sources including corrections)",
        occurrences: 5,
        category: "Deceased_Identifier",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'NHSNORSS',
        description: "NHSNO as given by Informant",
        occurrences: 1,
        category: "Deceased_Identifier",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'OCCDT',
        description: "Occupation of deceased text",
        occurrences: 1,
        category: "Deceased_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'OCCFFT',
        description: "Occupation of deceased free format text",
        occurrences: 4,
        category: "Deceased_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'OCCTYPE',
        description: "Occupation of deceased type",
        occurrences: 1,
        category: "Deceased_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'PCDR',
        description: "Postcode of usual residence of deceased",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'POBT',
        description: "Place of Birth text of deceased",
        occurrences: 1,
        category: "Deceased_Birth",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SEX',
        description: "(from Statistical DB),Coded sex of the deceased",
        occurrences: 1,
        category: "Deceased_Sex",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'SNAMD',
        description: "Surname of deceased",
        occurrences: 1,
        category: "Deceased_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'WARDR',
        description: "Ward code of usual residence of deceased",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'AGECS',
        description: "Calculated age of spouse",
        occurrences: 1,
        category: "Third party Non-professional_SpouseAge",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'EMPRSSDM',
        description: "Employment status of deceased of mother of a deceased juvenile (Pre SOC2000)",
        occurrences: 1,
        category: "Deceased or Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'EMPRSSHF',
        description: "Employment status of deceased's spouse or father of a deceased juvenile (Pre SOC2000)",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'EMPSECDM',
        description: "Employment status of deceased or mother of deceased juvenile SOC2000",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'EMPSECHF',
        description: "Employment status of deceased's spouse or father of a deceased juvenile SOC2000",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'EMPSTDM',
        description: "Employment status of deceased or mother of a deceased juvenile OCC90",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'EMPSTHF',
        description: "Employment status of deceased's spouse or father of a deceased juvenile OCC90",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'INDDMT',
        description: "Industry text for deceased or mother of a deceased juvenile",
        occurrences: 1,
        category: "Deceased or Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'INDHFT',
        description: "Industry text for deceased's spouse or Father of deceased juvenile ",
        occurrences: 1,
        category: "Deceased or Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'NAMEHF',
        description: "Name of spouse or father of a deceased juvenile",
        occurrences: 1,
        category: "Third party Non-professional_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'NAMEM',
        description: "Name of Mother of a deceased juvenile",
        occurrences: 1,
        category: "Third party Non-professional_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'OCC90DM',
        description: "Standard occupation classification code of deceased or mother of deceased juvenile - OCC90",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'OCC90HF',
        description: "Standard occupation classification code of deceased's spouse or father of deceased juvenile - OCC90",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'INDIRECT IDENTIFIER' },
      { name: 'OCCHFT',
        description: "Occupation of husband or father of deceased",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'OCCMT',
        description: "Occupation of Mother of deceased juvenile",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'RETINDM',
        description: "Retired indicator for deceased or mother of deceased juvenile",
        occurrences: 1,
        category: "Deceased or Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'RETINHF',
        description: "Retired indicator for deceased's spouse or father of deceased juvenile",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SCLASDM',
        description: "Social Class for deceased/mother of deceased juvenile",
        occurrences: 1,
        category: "Third party Non-professional_Socio-economic",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SCLASHF',
        description: "Social Class for spouse/father of deceased juvenile",
        occurrences: 1,
        category: "Third party Non-professional_Socio-economic",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SEC90DM',
        description: "Social economic classification for deceased/mother of juvenile (pre 2000)",
        occurrences: 1,
        category: "Third party Non-professional_Socio-economic",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SEC90HF',
        description: "Social economic classification for spouse/father of juvenile (pre 2000)",
        occurrences: 1,
        category: "Third party Non-professional_Socio-economic",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SECCATDM',
        description: "NS - SEC Social economic classification for deceased/mother of juvenile ",
        occurrences: 1,
        category: "Deceased or Third party Non-professional_Socio-economic",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SECCATHF',
        description: "NS- SEC Social economic classification for spouse/father of juvenile",
        occurrences: 1,
        category: "Third party Non-professional_Socio-economic",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SECCLRDM',
        description: "NS - SEC Social economic classification for deceased/mother of juvenile ",
        occurrences: 1,
        category: "Third party Non-professional_Socio-economic",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SECCLRHF',
        description: "NS- SEC Social economic classification for spouse/father of juvenile ",
        occurrences: 1,
        category: "Third party Non-professional_Socio-economic",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SOC2KDM',
        description: "Standard occupation classification of deceased or mother of deceased juvenile (SOC 2000). Since 2011, this field has contained the SOC2010 standard occupation classification",
        occurrences: 1,
        category: "Deceased or Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SOC2KHF',
        description: "Standard occupation classification of deceased's spouse or father of deceased juvenile (SOC 2000). Since 2011, this field has contained the SOC2010 standard occupation classification.",
        occurrences: 1,
        category: "Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SOC90DM',
        description: "OCC90 Standard Occupation classification of deceased or mother of deceased juvenile",
        occurrences: 1,
        category: "Deceased or Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'SOC90HF',
        description: "OCC90 Standard Occupation classification of deceased or mother of deceased juvenile",
        occurrences: 1,
        category: "Deceased or Third party Non-professional_Employment",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CERTTYPE',
        description: "Certification type",
        occurrences: 1,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CORAREAT',
        description: "Coroners area (Inquest)",
        occurrences: 1,
        category: "ProcessingEventOrProcess_Inquest",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CORCERTT',
        description: "Coroners certification text",
        occurrences: 1,
        category: "ProcessingEventOrProcess_Inquest",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'DOINQT',
        description: "Date of Inquest",
        occurrences: 1,
        category: "ProcessingEventOrProcess_Inquest",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'DOR',
        description: "Date of Registration",
        occurrences: 1,
        category: "ProcessingEventOrProcess_DeathRegistration",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'INQCERT',
        description: "Inquest certificate type",
        occurrences: 1,
        category: "ProcessingEventOrProcess_Inquest",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'POSTMORT',
        description: "Post mortem indicator",
        occurrences: 1,
        category: "ProcessingEventOrProcess_Postmortem",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CERTIFER',
        description: "Name and Qualifications of certifying Doctor on Medical Certificate ",
        occurrences: 1,
        category: "Professional_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'NAMEC',
        description: "Name of Coroner",
        occurrences: 1,
        category: "Professional_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'NAMECON',
        description: "Name of consultant (if applicable)",
        occurrences: 1,
        category: "Professional_Name",
        governance: 'DIRECT IDENTIFIER' },
      { name: 'CODFFT',
        description: "Up to 65 lines of cause of death free format text",
        occurrences: 65,
        category: "Death event_Mechanism",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CCG9POD',
        description: "Clinical Commissioning Group for place of death",
        occurrences: 1,
        category: "Death event__LocationArea",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'CCG9R',
        description: "Clinical Commissioning Group of usual residence",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'GOR9R',
        description: "Government office region code of usual residence of deceased",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' },
      { name: 'WARD9R',
        description: "Ward code of usual residence of deceased",
        occurrences: 1,
        category: "Deceased_Residence",
        governance: 'NON IDENTIFYING DATA' }
    ]
  end
end
