version: 0.0
os: linux
files:
  - source:  /
    destination: /tmp/mbis_front
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: script/code-deploy/ApplicationStop/stop_server.sh
      timeout: 300
  #BeforeInstall:
  #   - location: mbis_front/current/script/backup.sh
  #      timeout: 300
  AfterInstall:
    - location: script/code-deploy/AfterInstall/install_dependencies.sh
      timeout: 1800
  #   - location: mbis_front/current/script/migrate_database.sh
  #      timeout: 300
  #      runas: mbis_app
  ApplicationStart:
    - location: script/code-deploy/ApplicationStart/start_server.sh
      timeout: 300
      runas: mbis_app

  # AfterBlockTraffic
  # BeforeAllowTraffic
  # AfterAllowTraffic
  #   ValidateService:
  #     - location: Scripts/MonitorService.sh
  #       timeout: 3600
  #       runas: codedeployuser