version: "3.4"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres:14
    volumes:
      - db-data:/usr/local/pgsql/data
    environment:
      POSTGRES_USER: prescr_user
      POSTGRES_PASSWORD: prescr_user
      POSTGRES_DB: prescr_db
  app:
    env_file: .env
    build: .
    volumes:
      - .:/app
    ports:
      - 5001:5001
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://prescr_user:prescr_user@postgres/prescr_db