# Any difference in column name and field name is as a result of differences
# between the specifaction and sample data received
--- 
ncd: 
- column: centre
  unpack_pattern: a4
- column: year
  unpack_pattern: a2
- column: serial
  unpack_pattern: a5
- column: anniversaryyear
  unpack_pattern: a2
- column: surname
  mappings: 
  - replace: 
      ? !ruby/regexp /(\s*\/\s*|\s{2,})/
      : " "

    field: surname
  unpack_pattern: a50
- column: previoussurname
  mappings: 
  - replace: 
      ? !ruby/regexp /(\s*\/\s*|\s{2,})/
      : " "

    field: previoussurname
  unpack_pattern: a40
- column: forenames
  mappings: 
  - replace: 
      ? !ruby/regexp /(\s*\/\s*|\s{2,})/
      : " "

    field: forenames
  unpack_pattern: a62
- column: aliases
  unpack_pattern: a75
- standard_mapping: sex
  unpack_pattern: a1
- column: placeofbirth
  unpack_pattern: a60
- column: dateofbirth
  mappings: 
  - format: yyyymmdd
    field: dateofbirth
  unpack_pattern: a8
- column: dateofbirth_text
  unpack_pattern: a40
- column: address
  mappings: 
  - replace: 
      /: ","
    field: address
  unpack_pattern: a106
- column: postcode
  mappings: 
  - clean: :postcode
    field: postcode
  unpack_pattern: a7
- column: occupation
  unpack_pattern: a75
- column: occupation_husband_father
  unpack_pattern: a75
- column: occupation_mother
  unpack_pattern: a75
- column: dateofdeath
  mappings: 
  - format: yyyymmdd
    field: dateofdeath
  unpack_pattern: a8
- column: dateofdeath_text
  unpack_pattern: a40
- column: placeofdeath
  unpack_pattern: a106
- column: ons_text1a
  unpack_pattern: a75
- column: ons_text1b
  unpack_pattern: a75
- column: ons_text1c
  unpack_pattern: a75
- column: ons_text2
  unpack_pattern: a75
- column: ons_text
  unpack_pattern: a75
- column: ons_code1a
  unpack_pattern: a40
- column: ons_code1b
  unpack_pattern: a40
- column: ons_code1c
  unpack_pattern: a40
- column: ons_code2
  unpack_pattern: a40
- column: ons_code
  unpack_pattern: a40
- column: deathcausecode_underlying
  unpack_pattern: a4
- column: deathcausecode_significant
  unpack_pattern: a4
- column: registration_details
  unpack_pattern: a13
- column: certifier
  unpack_pattern: a50
- column: coronerscertificate
  unpack_pattern: a100
- column: coronersname
  unpack_pattern: a50
- column: coronersarea
  unpack_pattern: a100
- column: dateofinquest
  unpack_pattern: a50
- standard_mapping: nhsnumber
  unpack_pattern: a15
- column: spaces
  unpack_pattern: a10
- column: informantname
  unpack_pattern: a106
- column: informantaddress
  unpack_pattern: a106
- column: informantqualification
  unpack_pattern: a2
- column: informantqualification_text
  unpack_pattern: a40
- column: inquestcertificatetype
  unpack_pattern: a1
- column: inquestcertificatetype_text
  unpack_pattern: a12
- column: registrarsname
  unpack_pattern: a50
er: 
- column: centre
  unpack_pattern: a4
- column: year
  unpack_pattern: a2
- column: serial
  unpack_pattern: a5
- column: anniversaryyear
  unpack_pattern: a2
- column: recordtype
  unpack_pattern: a1
- column: errornumber
  unpack_pattern: a3
- column: errormessage
  mappings: 
  - join: ". "
    replace: 
      ? !ruby/regexp /(\s*\/\s*|\s{2,})/
      : " "

    field: comments
    order: 1
  unpack_pattern: a101
- column: errordetail
  mappings: 
  - replace: 
      ? !ruby/regexp /(\s*\/\s*|\s{2,})/
      : " "

    field: comments
    order: 2
  unpack_pattern: a98
cd: 
- column: generic_registrycode
  unpack_pattern: a2
- column: surname
  mappings: 
  - replace: 
      ? !ruby/regexp /(\s*\/\s*|\s{2,})/
      : " "

    field: surname
  unpack_pattern: a50
- column: previoussurname
  mappings: 
  - replace: 
      ? !ruby/regexp /(\s*\/\s*|\s{2,})/
      : " "

    field: previoussurname
  unpack_pattern: a40
- column: forenames
  mappings: 
  - replace: 
      ? !ruby/regexp /(\s*\/\s*|\s{2,})/
      : " "

    field: forenames
  unpack_pattern: a60
- column: aliases
  unpack_pattern: a75
- standard_mapping: sex
  unpack_pattern: a1
- column: placeofbirth
  unpack_pattern: a60
- column: dateofbirth
  mappings: 
  - format: yyyymmdd
    field: dateofbirth
  unpack_pattern: a8
- column: dateofbirth_text
  unpack_pattern: a40
- column: address
  mappings: 
  - replace: 
      /: ","
    field: address
  unpack_pattern: a106
- column: postcode
  mappings: 
  - clean: :postcode
    field: postcode
  unpack_pattern: a7
- column: occupation
  unpack_pattern: a75
# Column no longer in encore / CARA CSV file, fixed-width cancer deaths discontinued, plan.io #23600
# - column: occupation_husband_father
#   unpack_pattern: a75
- column: occupation_mother
  unpack_pattern: a75
- column: dateofdeath
  mappings: 
  - format: yyyymmdd
    field: dateofdeath
  unpack_pattern: a8
- column: dateofdeath_text
  unpack_pattern: a40
- column: placeofdeath
  unpack_pattern: a106
- column: ons_text1a
  unpack_pattern: a75
- column: ons_text1b
  unpack_pattern: a75
- column: ons_text1c
  unpack_pattern: a75
- column: ons_text2
  unpack_pattern: a75
- column: ons_text
  unpack_pattern: a75
- column: ons_code1a
  unpack_pattern: a40
- column: ons_code1b
  unpack_pattern: a40
- column: ons_code1c
  unpack_pattern: a40
- column: ons_code2
  unpack_pattern: a40
- column: ons_code
  unpack_pattern: a40
- column: deathcausecode_underlying
  unpack_pattern: a4
- column: deathcausecode_significant
  unpack_pattern: a4
- column: registration_details
  unpack_pattern: a13
- column: certifier
  unpack_pattern: a50
- column: coronerscertificate
  unpack_pattern: a100
- column: coronersname
  unpack_pattern: a50
- column: coronersarea
  unpack_pattern: a100
- column: dateofinquest
  unpack_pattern: a50
- column: informantqualification
  unpack_pattern: a2
- column: informantqualification_text
  unpack_pattern: a40
- column: inquestcertificatetype
  unpack_pattern: a1
- column: inquestcertificatetype_text
  unpack_pattern: a12
- standard_mapping: nhsnumber
  unpack_pattern: a10
- column: ageu1d # Needed for CARA, not in old encore fixed-format cancer deaths, plan.io #15123
  unpack_pattern: a10
