version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test

    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Copy database.yml
          command: |
            cp .circleci/database.yml config/database.yml
      - run: sudo apt update --fix-missing
      - run: sudo apt install -y postgresql-client || true
      - run: sudo apt install cmake
      - restore_cache:
          keys:
            - dms-{{ checksum "Gemfile.lock" }}
            - dms-
      - restore_cache:
          keys:
            - npm-cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-cache-{{ arch }}-{{ .Branch }}
            - npm-cache
      - restore_cache:
          keys:
            - asset-cache-{{ arch }}-{{ .Branch }}
            - asset-cache-
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: dms-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Install JS dependencies
          command: yarn install
      - save_cache:
          key: npm-cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Precompile assets
          command: RAILS_ENV=test bundle exec rails assets:precompile
      - save_cache:
          key: asset-cache-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - public/assets
            - tmp/cache/assets/sprockets
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:setup
      - run:
          name: Test suite
          command: bundle exec rake
      - run:
          name: Brakeman
          command: bundle exec brakeman
      - run:
          name: Bundle audit
          command: bundle exec bundle-audit check --update
      - slack/status:
          channel: CSEPN7EES
workflows:
  build_and_test:
    jobs:
      - build_and_test
