# Maps attributes from IdP SAML response to SP user model fields.
# See https://github.com/apokalipto/devise_saml_authenticatable for more.
default: &default {}

development:
  <<: *default

test:
  <<: *default

production:
  objectGuid: object_guid
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn": upn
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": email
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": first_name
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname": last_name
