# This file tracks which SVN branch should be deployed to which targets, under which Ruby version.
# The format is <ENV>: { branch: <BRANCH>, ruby: <RUBY> }, where all deployment targets can be
# stratified by <ENV>, <BRANCH> is branch of the MBIS project and <RUBY> is the server Ruby.
---
beta:
  branch: 'master'
  ruby: 2.7.3
live:
  branch: 'master'
  ruby: 2.7.3
