---
? !ruby/regexp /.*/
:
  prescr_data:
    root: <%= Rails.root.join('private', 'prescr_data') %>
    prms: [r, w, x]
  mbis_data:
    # For MBIS births / deaths imports, and data releases
    root: <%= Rails.root.join('private', 'mbis_data') %>
    prms: [r, w]
  mappings_config:
    root: "<%= Rails.root.join('config', 'mappings') %>"
    prms: [r]
  h_drive:
    # root: "/Volumes/Share/Electronic Data"
    root: <%= Rails.root.join('private').join('h_drive') %>
    prms: [r, w]
  key_bundles:
    root: <%= Rails.root.join('config', 'keys') %>
    prms: [r]
  pseudonymised_data:
    # Pseudonymised BRCA data
    root: <%= Rails.root.join('private', 'pseudonymised_data') %>
    prms: [r, w]
  xml_files:
    root: <%= Rails.root.join('test', 'xml_files') %>
    prms: [r]
  tmp:
    root: <%= Rails.root.join('tmp') %>
    prms: [r]
  db_files:
    root: <%= Rails.root.join('db', 'files') %>
    prms: [r]
  test_files:
    root: <%= Rails.root.join('test', 'models', 'test_files') %>
    prms: [r]
    