class AddColumnsToPseudoBirthData < ActiveRecord::Migration[5.0]
  def change
    add_column :birth_data, :mbism204id, :string
    add_column :birth_data, :ledrid, :integer
    add_column :birth_data, :birthwgt, :integer
    add_column :birth_data, :caind, :string
    add_column :birth_data, :ccgpob, :string
    add_column :birth_data, :cestrss, :string
    add_column :birth_data, :ctypob, :string
    add_column :birth_data, :dobf, :string
    add_column :birth_data, :dor, :string
    add_column :birth_data, :esttypeb, :string
    add_column :birth_data, :hautpob, :string
    add_column :birth_data, :hropob, :string
    add_column :birth_data, :loarpob, :string
    add_column :birth_data, :lsoarpob, :string
    add_column :birth_data, :multbth, :integer
    add_column :birth_data, :multtype, :integer
    add_column :birth_data, :nhsind, :integer
    add_column :birth_data, :pcdpob, :string
    add_column :birth_data, :pobt, :string
    add_column :birth_data, :sbind, :integer
    add_column :birth_data, :dob, :string
    add_column :birth_data, :fnamch1, :string
    add_column :birth_data, :fnamch2, :string
    add_column :birth_data, :fnamch3, :string
    add_column :birth_data, :fnamchx_1, :string
    add_column :birth_data, :fnamchx_2, :string
    add_column :birth_data, :gestatn, :integer
    add_column :birth_data, :icdpv_1, :string
    add_column :birth_data, :icdpv_2, :string
    add_column :birth_data, :icdpv_3, :string
    add_column :birth_data, :icdpv_4, :string
    add_column :birth_data, :icdpv_5, :string
    add_column :birth_data, :icdpv_6, :string
    add_column :birth_data, :icdpv_7, :string
    add_column :birth_data, :icdpv_8, :string
    add_column :birth_data, :icdpv_9, :string
    add_column :birth_data, :icdpv_10, :string
    add_column :birth_data, :icdpv_11, :string
    add_column :birth_data, :icdpv_12, :string
    add_column :birth_data, :icdpv_13, :string
    add_column :birth_data, :icdpv_14, :string
    add_column :birth_data, :icdpv_15, :string
    add_column :birth_data, :icdpv_16, :string
    add_column :birth_data, :icdpv_17, :string
    add_column :birth_data, :icdpv_18, :string
    add_column :birth_data, :icdpv_19, :string
    add_column :birth_data, :icdpv_20, :string
    add_column :birth_data, :icdpvf_1, :string
    add_column :birth_data, :icdpvf_2, :string
    add_column :birth_data, :icdpvf_3, :string
    add_column :birth_data, :icdpvf_4, :string
    add_column :birth_data, :icdpvf_5, :string
    add_column :birth_data, :icdpvf_6, :string
    add_column :birth_data, :icdpvf_7, :string
    add_column :birth_data, :icdpvf_8, :string
    add_column :birth_data, :icdpvf_9, :string
    add_column :birth_data, :icdpvf_10, :string
    add_column :birth_data, :icdpvf_11, :string
    add_column :birth_data, :icdpvf_12, :string
    add_column :birth_data, :icdpvf_13, :string
    add_column :birth_data, :icdpvf_14, :string
    add_column :birth_data, :icdpvf_15, :string
    add_column :birth_data, :icdpvf_16, :string
    add_column :birth_data, :icdpvf_17, :string
    add_column :birth_data, :icdpvf_18, :string
    add_column :birth_data, :icdpvf_19, :string
    add_column :birth_data, :icdpvf_20, :string
    add_column :birth_data, :nhsno, :string
    add_column :birth_data, :sex, :integer
    add_column :birth_data, :snamch, :string
    add_column :birth_data, :cod10r_1, :string
    add_column :birth_data, :cod10r_2, :string
    add_column :birth_data, :cod10r_3, :string
    add_column :birth_data, :cod10r_4, :string
    add_column :birth_data, :cod10r_5, :string
    add_column :birth_data, :cod10r_6, :string
    add_column :birth_data, :cod10r_7, :string
    add_column :birth_data, :cod10r_8, :string
    add_column :birth_data, :cod10r_9, :string
    add_column :birth_data, :cod10r_10, :string
    add_column :birth_data, :cod10r_11, :string
    add_column :birth_data, :cod10r_12, :string
    add_column :birth_data, :cod10r_13, :string
    add_column :birth_data, :cod10r_14, :string
    add_column :birth_data, :cod10r_15, :string
    add_column :birth_data, :cod10r_16, :string
    add_column :birth_data, :cod10r_17, :string
    add_column :birth_data, :cod10r_18, :string
    add_column :birth_data, :cod10r_19, :string
    add_column :birth_data, :cod10r_20, :string
    add_column :birth_data, :codfft_1, :string
    add_column :birth_data, :codfft_2, :string
    add_column :birth_data, :codfft_3, :string
    add_column :birth_data, :codfft_4, :string
    add_column :birth_data, :codfft_5, :string
    add_column :birth_data, :deathlab, :string
    add_column :birth_data, :wigwo10, :integer
    add_column :birth_data, :addrmt, :string
    add_column :birth_data, :agebf, :string
    add_column :birth_data, :agebm, :string
    add_column :birth_data, :agemf, :string
    add_column :birth_data, :agemm, :string
    add_column :birth_data, :bthimar, :string
    add_column :birth_data, :ccgrm, :string
    add_column :birth_data, :ctrypobf, :string
    add_column :birth_data, :ctrypobm, :string
    add_column :birth_data, :ctydrm, :string
    add_column :birth_data, :ctyrm, :string
    add_column :birth_data, :dobm, :string
    add_column :birth_data, :durmar, :integer
    add_column :birth_data, :empsecf, :string
    add_column :birth_data, :empsecm, :string
    add_column :birth_data, :empstf, :string
    add_column :birth_data, :empstm, :string
    add_column :birth_data, :fnamf_1, :string
    add_column :birth_data, :fnamf_2, :string
    add_column :birth_data, :fnamf_3, :string
    add_column :birth_data, :fnamfx_1, :string
    add_column :birth_data, :fnamfx_2, :string
    add_column :birth_data, :fnamm_1, :string
    add_column :birth_data, :fnamm_2, :string
    add_column :birth_data, :fnamm_3, :string
    add_column :birth_data, :fnammx_1, :string
    add_column :birth_data, :fnammx_2, :string
    add_column :birth_data, :gorrm, :string
    add_column :birth_data, :hautrm, :string
    add_column :birth_data, :hrorm, :string
    add_column :birth_data, :loarm, :string
    add_column :birth_data, :lsoarm, :string
    add_column :birth_data, :namemaid, :string
    add_column :birth_data, :pcdrm, :string
    add_column :birth_data, :seccatf, :string
    add_column :birth_data, :seccatm, :string
    add_column :birth_data, :snamf, :string
    add_column :birth_data, :snamm, :string
    add_column :birth_data, :snammcf, :string
    add_column :birth_data, :soc2kf, :string
    add_column :birth_data, :soc2km, :string
    add_column :birth_data, :soc90f, :string
    add_column :birth_data, :soc90m, :string
    add_column :birth_data, :stregrm, :string
    add_column :birth_data, :wardrm, :string
  end
end
