class AddColumnsToPseudoDeathData < ActiveRecord::Migration[5.0]
  def change
    add_column :death_data, :mbism204id, :string
    add_column :death_data, :ledrid, :integer
    add_column :death_data, :cestrssr, :string
    add_column :death_data, :ceststay, :string
    add_column :death_data, :ccgpod, :string
    add_column :death_data, :cestrss, :string
    add_column :death_data, :cod10r_1, :integer
    add_column :death_data, :cod10r_2, :integer
    add_column :death_data, :cod10r_3, :integer
    add_column :death_data, :cod10r_4, :integer
    add_column :death_data, :cod10r_5, :integer
    add_column :death_data, :cod10r_6, :integer
    add_column :death_data, :cod10r_7, :integer
    add_column :death_data, :cod10r_8, :integer
    add_column :death_data, :cod10r_9, :integer
    add_column :death_data, :cod10r_10, :integer
    add_column :death_data, :cod10r_11, :integer
    add_column :death_data, :cod10r_12, :integer
    add_column :death_data, :cod10r_13, :integer
    add_column :death_data, :cod10r_14, :integer
    add_column :death_data, :cod10r_15, :integer
    add_column :death_data, :cod10r_16, :integer
    add_column :death_data, :cod10r_17, :integer
    add_column :death_data, :cod10r_18, :integer
    add_column :death_data, :cod10r_19, :integer
    add_column :death_data, :cod10r_20, :integer
    add_column :death_data, :cod10rf_1, :integer
    add_column :death_data, :cod10rf_2, :integer
    add_column :death_data, :cod10rf_3, :integer
    add_column :death_data, :cod10rf_4, :integer
    add_column :death_data, :cod10rf_5, :integer
    add_column :death_data, :cod10rf_6, :integer
    add_column :death_data, :cod10rf_7, :integer
    add_column :death_data, :cod10rf_8, :integer
    add_column :death_data, :cod10rf_9, :integer
    add_column :death_data, :cod10rf_10, :integer
    add_column :death_data, :cod10rf_11, :integer
    add_column :death_data, :cod10rf_12, :integer
    add_column :death_data, :cod10rf_13, :integer
    add_column :death_data, :cod10rf_14, :integer
    add_column :death_data, :cod10rf_15, :integer
    add_column :death_data, :cod10rf_16, :integer
    add_column :death_data, :cod10rf_17, :integer
    add_column :death_data, :cod10rf_18, :integer
    add_column :death_data, :cod10rf_19, :integer
    add_column :death_data, :cod10rf_20, :integer
    add_column :death_data, :codt_1, :string
    add_column :death_data, :codt_2, :string
    add_column :death_data, :codt_3, :string
    add_column :death_data, :codt_4, :string
    add_column :death_data, :codt_5, :string
    add_column :death_data, :ctydpod, :integer
    add_column :death_data, :ctypod, :integer
    add_column :death_data, :dester, :string
    add_column :death_data, :doddy, :integer
    add_column :death_data, :dodmt, :integer
    add_column :death_data, :dodyr, :integer
    add_column :death_data, :esttyped, :string
    add_column :death_data, :hautpod, :string
    add_column :death_data, :hropod, :string
    add_column :death_data, :icd_1, :string
    add_column :death_data, :icd_2, :string
    add_column :death_data, :icd_3, :string
    add_column :death_data, :icd_4, :string
    add_column :death_data, :icd_5, :string
    add_column :death_data, :icd_6, :string
    add_column :death_data, :icd_7, :string
    add_column :death_data, :icd_8, :string
    add_column :death_data, :icd_9, :string
    add_column :death_data, :icd_10, :string
    add_column :death_data, :icd_11, :string
    add_column :death_data, :icd_12, :string
    add_column :death_data, :icd_13, :string
    add_column :death_data, :icd_14, :string
    add_column :death_data, :icd_15, :string
    add_column :death_data, :icd_16, :string
    add_column :death_data, :icd_17, :string
    add_column :death_data, :icd_18, :string
    add_column :death_data, :icd_19, :string
    add_column :death_data, :icd_20, :string
    add_column :death_data, :icdf_1, :string
    add_column :death_data, :icdf_2, :string
    add_column :death_data, :icdf_3, :string
    add_column :death_data, :icdf_4, :string
    add_column :death_data, :icdf_5, :string
    add_column :death_data, :icdf_6, :string
    add_column :death_data, :icdf_7, :string
    add_column :death_data, :icdf_8, :string
    add_column :death_data, :icdf_9, :string
    add_column :death_data, :icdf_10, :string
    add_column :death_data, :icdf_11, :string
    add_column :death_data, :icdf_12, :string
    add_column :death_data, :icdf_13, :string
    add_column :death_data, :icdf_14, :string
    add_column :death_data, :icdf_15, :string
    add_column :death_data, :icdf_16, :string
    add_column :death_data, :icdf_17, :string
    add_column :death_data, :icdf_18, :string
    add_column :death_data, :icdf_19, :string
    add_column :death_data, :icdf_20, :string
    add_column :death_data, :icdpv_1, :string
    add_column :death_data, :icdpv_2, :string
    add_column :death_data, :icdpv_3, :string
    add_column :death_data, :icdpv_4, :string
    add_column :death_data, :icdpv_5, :string
    add_column :death_data, :icdpv_6, :string
    add_column :death_data, :icdpv_7, :string
    add_column :death_data, :icdpv_8, :string
    add_column :death_data, :icdpv_9, :string
    add_column :death_data, :icdpv_10, :string
    add_column :death_data, :icdpv_11, :string
    add_column :death_data, :icdpv_12, :string
    add_column :death_data, :icdpv_13, :string
    add_column :death_data, :icdpv_14, :string
    add_column :death_data, :icdpv_15, :string
    add_column :death_data, :icdpv_16, :string
    add_column :death_data, :icdpv_17, :string
    add_column :death_data, :icdpv_18, :string
    add_column :death_data, :icdpv_19, :string
    add_column :death_data, :icdpv_20, :string
    add_column :death_data, :icdpvf_1, :string
    add_column :death_data, :icdpvf_2, :string
    add_column :death_data, :icdpvf_3, :string
    add_column :death_data, :icdpvf_4, :string
    add_column :death_data, :icdpvf_5, :string
    add_column :death_data, :icdpvf_6, :string
    add_column :death_data, :icdpvf_7, :string
    add_column :death_data, :icdpvf_8, :string
    add_column :death_data, :icdpvf_9, :string
    add_column :death_data, :icdpvf_10, :string
    add_column :death_data, :icdpvf_11, :string
    add_column :death_data, :icdpvf_12, :string
    add_column :death_data, :icdpvf_13, :string
    add_column :death_data, :icdpvf_14, :string
    add_column :death_data, :icdpvf_15, :string
    add_column :death_data, :icdpvf_16, :string
    add_column :death_data, :icdpvf_17, :string
    add_column :death_data, :icdpvf_18, :string
    add_column :death_data, :icdpvf_19, :string
    add_column :death_data, :icdpvf_20, :string
    add_column :death_data, :icdsc, :string
    add_column :death_data, :icdscf, :string
    add_column :death_data, :icdu, :string
    add_column :death_data, :icduf, :string
    add_column :death_data, :icdfuture1, :string
    add_column :death_data, :icdfuture2, :string
    add_column :death_data, :lineno9_1, :integer
    add_column :death_data, :lineno9_2, :integer
    add_column :death_data, :lineno9_3, :integer
    add_column :death_data, :lineno9_4, :integer
    add_column :death_data, :lineno9_5, :integer
    add_column :death_data, :lineno9_6, :integer
    add_column :death_data, :lineno9_7, :integer
    add_column :death_data, :lineno9_8, :integer
    add_column :death_data, :lineno9_9, :integer
    add_column :death_data, :lineno9_10, :integer
    add_column :death_data, :lineno9_11, :integer
    add_column :death_data, :lineno9_12, :integer
    add_column :death_data, :lineno9_13, :integer
    add_column :death_data, :lineno9_14, :integer
    add_column :death_data, :lineno9_15, :integer
    add_column :death_data, :lineno9_16, :integer
    add_column :death_data, :lineno9_17, :integer
    add_column :death_data, :lineno9_18, :integer
    add_column :death_data, :lineno9_19, :integer
    add_column :death_data, :lineno9_20, :integer
    add_column :death_data, :lineno9f_1, :integer
    add_column :death_data, :lineno9f_2, :integer
    add_column :death_data, :lineno9f_3, :integer
    add_column :death_data, :lineno9f_4, :integer
    add_column :death_data, :lineno9f_5, :integer
    add_column :death_data, :lineno9f_6, :integer
    add_column :death_data, :lineno9f_7, :integer
    add_column :death_data, :lineno9f_8, :integer
    add_column :death_data, :lineno9f_9, :integer
    add_column :death_data, :lineno9f_10, :integer
    add_column :death_data, :lineno9f_11, :integer
    add_column :death_data, :lineno9f_12, :integer
    add_column :death_data, :lineno9f_13, :integer
    add_column :death_data, :lineno9f_14, :integer
    add_column :death_data, :lineno9f_15, :integer
    add_column :death_data, :lineno9f_16, :integer
    add_column :death_data, :lineno9f_17, :integer
    add_column :death_data, :lineno9f_18, :integer
    add_column :death_data, :lineno9f_19, :integer
    add_column :death_data, :lineno9f_20, :integer
    add_column :death_data, :loapod, :string
    add_column :death_data, :lsoapod, :string
    add_column :death_data, :nhsind, :string
    add_column :death_data, :pcdpod, :string
    add_column :death_data, :ploacc10, :integer
    add_column :death_data, :podqual, :string
    add_column :death_data, :podt, :string
    add_column :death_data, :wigwo10, :string
    add_column :death_data, :wigwo10f, :string
    add_column :death_data, :addrdt, :string
    add_column :death_data, :agec, :integer
    add_column :death_data, :agecunit, :integer
    add_column :death_data, :ageu1d, :string
    add_column :death_data, :aksnamd_1, :string
    add_column :death_data, :aksnamd_2, :string
    add_column :death_data, :aksnamd_3, :string
    add_column :death_data, :aksnamd_4, :string
    add_column :death_data, :aksnamd_5, :string
    add_column :death_data, :akfnamd_1_1, :string
    add_column :death_data, :akfnamd_1_2, :string
    add_column :death_data, :akfnamd_1_3, :string
    add_column :death_data, :akfnamd_1_4, :string
    add_column :death_data, :akfnamd_1_5, :string
    add_column :death_data, :akfnamd_2_1, :string
    add_column :death_data, :akfnamd_2_2, :string
    add_column :death_data, :akfnamd_2_3, :string
    add_column :death_data, :akfnamd_2_4, :string
    add_column :death_data, :akfnamd_2_5, :string
    add_column :death_data, :akfnamd_3_1, :string
    add_column :death_data, :akfnamd_3_2, :string
    add_column :death_data, :akfnamd_3_3, :string
    add_column :death_data, :akfnamd_3_4, :string
    add_column :death_data, :akfnamd_3_5, :string
    add_column :death_data, :akfndi_1, :string
    add_column :death_data, :akfndi_2, :string
    add_column :death_data, :akfndi_3, :string
    add_column :death_data, :akfndi_4, :string
    add_column :death_data, :akfndi_5, :string
    add_column :death_data, :aliasd_1, :string
    add_column :death_data, :aliasd_2, :string
    add_column :death_data, :ccgr, :string
    add_column :death_data, :ctrypob, :integer
    add_column :death_data, :ctryr, :integer
    add_column :death_data, :ctydr, :integer
    add_column :death_data, :ctyr, :integer
    add_column :death_data, :dobdy, :integer
    add_column :death_data, :dobmt, :integer
    add_column :death_data, :dobyr, :integer
    add_column :death_data, :fnamd1, :string
    add_column :death_data, :fnamd2, :string
    add_column :death_data, :fnamd3, :string
    add_column :death_data, :fnamdx_1, :string
    add_column :death_data, :fnamdx_2, :string
    add_column :death_data, :gorr, :string
    add_column :death_data, :hautr, :string
    add_column :death_data, :hror, :string
    add_column :death_data, :loar, :string
    add_column :death_data, :lsoar, :string
    add_column :death_data, :marstat, :integer
    add_column :death_data, :namemaid, :string
    add_column :death_data, :nhsno_1, :string
    add_column :death_data, :nhsno_2, :string
    add_column :death_data, :nhsno_3, :string
    add_column :death_data, :nhsno_4, :string
    add_column :death_data, :nhsno_5, :string
    add_column :death_data, :nhsnorss, :string
    add_column :death_data, :occdt, :string
    add_column :death_data, :occfft_1, :string
    add_column :death_data, :occfft_2, :string
    add_column :death_data, :occfft_3, :string
    add_column :death_data, :occfft_4, :string
    add_column :death_data, :occtype, :string
    add_column :death_data, :pcdr, :string
    add_column :death_data, :pobt, :string
    add_column :death_data, :sex, :integer
    add_column :death_data, :snamd, :string
    add_column :death_data, :wardr, :string
    add_column :death_data, :agecs, :integer
    add_column :death_data, :emprssdm, :string
    add_column :death_data, :emprsshf, :string
    add_column :death_data, :empsecdm, :string
    add_column :death_data, :empsechf, :string
    add_column :death_data, :empstdm, :string
    add_column :death_data, :empsthf, :string
    add_column :death_data, :inddmt, :string
    add_column :death_data, :indhft, :string
    add_column :death_data, :namehf, :string
    add_column :death_data, :namem, :string
    add_column :death_data, :occ90dm, :string
    add_column :death_data, :occ90hf, :string
    add_column :death_data, :occhft, :string
    add_column :death_data, :occmt, :string
    add_column :death_data, :retindm, :integer
    add_column :death_data, :retindhf, :integer
    add_column :death_data, :sclasdm, :string
    add_column :death_data, :sclashf, :string
    add_column :death_data, :sec90dm, :string
    add_column :death_data, :sec90hf, :string
    add_column :death_data, :seccatdm, :string
    add_column :death_data, :seccathf, :string
    add_column :death_data, :secclrdm, :string
    add_column :death_data, :secclrhf, :string
    add_column :death_data, :soc2kdm, :string
    add_column :death_data, :soc2khf, :string
    add_column :death_data, :soc90dm, :string
    add_column :death_data, :soc90hf, :string
    add_column :death_data, :certtype, :integer
    add_column :death_data, :corareat, :string
    add_column :death_data, :corcertt, :string
    add_column :death_data, :doinqt, :string
    add_column :death_data, :dor, :string
    add_column :death_data, :inqcert, :integer
    add_column :death_data, :postmort, :integer
    add_column :death_data, :certifer, :string
    add_column :death_data, :namec, :string
    add_column :death_data, :namecon, :string
    add_column :death_data, :codfft_1, :string
    add_column :death_data, :codfft_2, :string
    add_column :death_data, :codfft_3, :string
    add_column :death_data, :codfft_4, :string
    add_column :death_data, :codfft_5, :string
    add_column :death_data, :codfft_6, :string
    add_column :death_data, :codfft_7, :string
    add_column :death_data, :codfft_8, :string
    add_column :death_data, :codfft_9, :string
    add_column :death_data, :codfft_10, :string
    add_column :death_data, :codfft_11, :string
    add_column :death_data, :codfft_12, :string
    add_column :death_data, :codfft_13, :string
    add_column :death_data, :codfft_14, :string
    add_column :death_data, :codfft_15, :string
    add_column :death_data, :codfft_16, :string
    add_column :death_data, :codfft_17, :string
    add_column :death_data, :codfft_18, :string
    add_column :death_data, :codfft_19, :string
    add_column :death_data, :codfft_20, :string
    add_column :death_data, :codfft_21, :string
    add_column :death_data, :codfft_22, :string
    add_column :death_data, :codfft_23, :string
    add_column :death_data, :codfft_24, :string
    add_column :death_data, :codfft_25, :string
    add_column :death_data, :codfft_26, :string
    add_column :death_data, :codfft_27, :string
    add_column :death_data, :codfft_28, :string
    add_column :death_data, :codfft_29, :string
    add_column :death_data, :codfft_30, :string
    add_column :death_data, :codfft_31, :string
    add_column :death_data, :codfft_32, :string
    add_column :death_data, :codfft_33, :string
    add_column :death_data, :codfft_34, :string
    add_column :death_data, :codfft_35, :string
    add_column :death_data, :codfft_36, :string
    add_column :death_data, :codfft_37, :string
    add_column :death_data, :codfft_38, :string
    add_column :death_data, :codfft_39, :string
    add_column :death_data, :codfft_40, :string
    add_column :death_data, :codfft_41, :string
    add_column :death_data, :codfft_42, :string
    add_column :death_data, :codfft_43, :string
    add_column :death_data, :codfft_44, :string
    add_column :death_data, :codfft_45, :string
    add_column :death_data, :codfft_46, :string
    add_column :death_data, :codfft_47, :string
    add_column :death_data, :codfft_48, :string
    add_column :death_data, :codfft_49, :string
    add_column :death_data, :codfft_50, :string
    add_column :death_data, :codfft_51, :string
    add_column :death_data, :codfft_52, :string
    add_column :death_data, :codfft_53, :string
    add_column :death_data, :codfft_54, :string
    add_column :death_data, :codfft_55, :string
    add_column :death_data, :codfft_56, :string
    add_column :death_data, :codfft_57, :string
    add_column :death_data, :codfft_58, :string
    add_column :death_data, :codfft_59, :string
    add_column :death_data, :codfft_60, :string
    add_column :death_data, :codfft_61, :string
    add_column :death_data, :codfft_62, :string
    add_column :death_data, :codfft_63, :string
    add_column :death_data, :codfft_64, :string
    add_column :death_data, :codfft_65, :string
  end
end
