class PopulateRecCommittees < ActiveRecord::Migration[5.2]
  include MigrationHelper
  
  class RecCommittee < ApplicationRecord
    attribute :value, :string
  end

  def change
    add_lookup RecCommittee, 1, value: 'East Midlands - Derby'
    add_lookup RecCommittee, 2, value: 'East Midlands - Leicester Central'
    add_lookup RecCommittee, 3, value: 'East Midlands - Leicester South'
    add_lookup RecCommittee, 4, value: 'East Midlands - Nottingham 1'
    add_lookup RecCommittee, 5, value: 'East Midlands - Nottingham 2'
    add_lookup RecCommittee, 6, value: 'East of England - Cambridgeshire and Hertfordshire'
    add_lookup RecCommittee, 7, value: 'East of England - Essex'
    add_lookup RecCommittee, 8, value: 'East of England - Cambridge Central'
    add_lookup RecCommittee, 9, value: 'East of England - Cambridge East'
    add_lookup RecCommittee, 10, value: 'East of England - Cambridge South'
    add_lookup RecCommittee, 11, value: 'East of Scotland Research Ethics Service REC 1'
    add_lookup RecCommittee, 12, value: 'East of Scotland Research Ethics Service REC 2'
    add_lookup RecCommittee, 13, value: 'Health and Social Care Research Ethics Committee A (HSC REC A)'
    add_lookup RecCommittee, 14, value: 'Health and Social Care Research Ethics Committee B (HSC REC B)'
    add_lookup RecCommittee, 15, value: 'London - Bloomsbury'
    add_lookup RecCommittee, 16, value: 'London - Camden and Kings Cross'
    add_lookup RecCommittee, 17, value: 'London - Central'
    add_lookup RecCommittee, 18, value: 'London - Brent'
    add_lookup RecCommittee, 19, value: 'London - Bromley'
    add_lookup RecCommittee, 20, value: 'London - Camberwell St Gile'
    add_lookup RecCommittee, 21, value: 'London - Chelsea'
    add_lookup RecCommittee, 22, value: 'London - City and East'
    add_lookup RecCommittee, 23, value: 'London - Dulwich'
    add_lookup RecCommittee, 24, value: 'London - Fulham'
    add_lookup RecCommittee, 25, value: 'London - Hampstead'
    add_lookup RecCommittee, 26, value: 'London - Harrow'
    add_lookup RecCommittee, 27, value: 'London - London Bridge'
    add_lookup RecCommittee, 28, value: 'London - Queen Square'
    add_lookup RecCommittee, 29, value: 'London - Riverside'
    add_lookup RecCommittee, 30, value: 'London - South East'
    add_lookup RecCommittee, 31, value: 'London - Stanmore'
    add_lookup RecCommittee, 32, value: 'London - Surrey Borders'
    add_lookup RecCommittee, 33, value: 'London - West London & GTAC'
    add_lookup RecCommittee, 34, value: 'London - Westminster'
    add_lookup RecCommittee, 35, value: 'National Social Care Research Ethics Committee'
    add_lookup RecCommittee, 36, value: 'North East - Newcastle and North Tyneside 1'
    add_lookup RecCommittee, 37, value: 'North East - Newcastle and North Tyneside 2'
    add_lookup RecCommittee, 38, value: 'North East - Tyne & Wear South'
    add_lookup RecCommittee, 39, value: 'North East - York'
    add_lookup RecCommittee, 40, value: 'North of Scotland Research Ethics Committee 1'
    add_lookup RecCommittee, 41, value: 'North of Scotland Research Ethics Committee 2'
    add_lookup RecCommittee, 42, value: 'North West - GM Central'
    add_lookup RecCommittee, 43, value: 'North West - GM East'
    add_lookup RecCommittee, 44, value: 'North West - GM South'
    add_lookup RecCommittee, 45, value: 'North West - GM West'
    add_lookup RecCommittee, 46, value: 'North West - Haydock'
    add_lookup RecCommittee, 47, value: 'North West - Lancaster'
    add_lookup RecCommittee, 48, value: 'North West - Liverpool Central'
    add_lookup RecCommittee, 49, value: 'North West - Liverpool East'
    add_lookup RecCommittee, 50, value: 'North West - Preston'
    add_lookup RecCommittee, 51, value: 'Scotland A Research Ethics Committee'
    add_lookup RecCommittee, 52, value: 'South Central - Berkshire B'
    add_lookup RecCommittee, 53, value: 'South Central - Hampshire A'
    add_lookup RecCommittee, 54, value: 'South Central - Hampshire B'
    add_lookup RecCommittee, 55, value: 'South Central - Berkshire'
    add_lookup RecCommittee, 56, value: 'South Central - Oxford A'
    add_lookup RecCommittee, 57, value: 'South Central - Oxford B'
    add_lookup RecCommittee, 58, value: 'South Central - Oxford C'
    add_lookup RecCommittee, 59, value: 'South East Coast - Brighton and Sussex'
    add_lookup RecCommittee, 60, value: 'South East Coast - Surrey'
    add_lookup RecCommittee, 61, value: 'South East Scotland Research Ethics Committee 1'
    add_lookup RecCommittee, 62, value: 'South East Scotland Research Ethics Committee 2'
    add_lookup RecCommittee, 63, value: 'South West - Central Bristol'
    add_lookup RecCommittee, 64, value: 'South West - Cornwall and Plymouth'
    add_lookup RecCommittee, 65, value: 'South West - Exeter'
    add_lookup RecCommittee, 66, value: 'South West - Frenchay'
    add_lookup RecCommittee, 67, value: 'Wales REC 1'
    add_lookup RecCommittee, 68, value: 'Wales REC 2'
    add_lookup RecCommittee, 69, value: 'Wales REC 3'
    add_lookup RecCommittee, 70, value: 'Wales REC 4'
    add_lookup RecCommittee, 71, value: 'Wales REC 5'
    add_lookup RecCommittee, 72, value: 'Wales REC 6'
    add_lookup RecCommittee, 73, value: 'Wales REC 7'
    add_lookup RecCommittee, 74, value: 'West Midlands - Edgbaston'
    add_lookup RecCommittee, 75, value: 'West Midlands - Coventry and Warwickshire'
    add_lookup RecCommittee, 76, value: 'West Midlands - Solihull'
    add_lookup RecCommittee, 77, value: 'West Midlands - South Birmingham'
    add_lookup RecCommittee, 78, value: 'West Midlands - The Black Country'
    add_lookup RecCommittee, 79, value: 'West of Scotland REC 1'
    add_lookup RecCommittee, 80, value: 'West of Scotland REC 3'
    add_lookup RecCommittee, 81, value: 'West of Scotland REC 4'
    add_lookup RecCommittee, 82, value: 'West of Scotland REC 5'
    add_lookup RecCommittee, 83, value: 'Yorkshire and the Humber - Bradford Leeds'
    add_lookup RecCommittee, 84, value: 'Yorkshire and the Humber - Leeds East'
    add_lookup RecCommittee, 85, value: 'Yorkshire and the Humber - Leeds West'
    add_lookup RecCommittee, 86, value: 'Yorkshire and the Humber - Sheffield'
    add_lookup RecCommittee, 87, value: 'Yorkshire and the Humber - South Yorkshire'
    add_lookup RecCommittee, 88, value: 'CPRD Independent Scientific Advisory Committee'
    add_lookup RecCommittee, 89, value: 'MREC - London'
    add_lookup RecCommittee, 90, value: 'Other'
  end
end
