# Country lookup table lifted from ONS
# https://www.ons.gov.uk/methodology/classificationsandstandards/otherclassifications/nationalstatisticscountryclassification
class PopulateCountries < ActiveRecord::Migration[5.2]
  include MigrationHelper
  
  class Country < ApplicationRecord
    attribute :value, :string
  end

  def change
    add_lookup Country, 'AFG', value: 'AFGHANISTAN'
    add_lookup Country, 'ALA', value: 'ÅLAND ISLANDS'
    add_lookup Country, 'ALB', value: 'ALBANIA'
    add_lookup Country, 'DZA', value: 'ALGERIA'
    add_lookup Country, 'ASM', value: 'AMERICAN SAMOA'
    add_lookup Country, 'AND', value: 'ANDORRA'
    add_lookup Country, 'AGO', value: 'ANGOLA'
    add_lookup Country, 'AIA', value: 'ANGUILLA'
    add_lookup Country, 'ATA', value: 'ANTARCTICA'
    add_lookup Country, 'ATG', value: 'ANTIGUA AND BARBUDA'
    add_lookup Country, 'ARG', value: 'ARGENTINA'
    add_lookup Country, 'ARM', value: 'ARMENIA'
    add_lookup Country, 'ABW', value: 'ARUBA'
    add_lookup Country, 'AUS', value: 'AUSTRALIA'
    add_lookup Country, 'AUT', value: 'AUSTRIA'
    add_lookup Country, 'AZE', value: 'AZERBAIJAN'
    add_lookup Country, 'BHS', value: 'BAHAMAS, THE'
    add_lookup Country, 'BHR', value: 'BAHRAIN'
    add_lookup Country, 'BGD', value: 'BANGLADESH'
    add_lookup Country, 'BRB', value: 'BARBADOS'
    add_lookup Country, 'BLR', value: 'BELARUS'
    add_lookup Country, 'BEL', value: 'BELGIUM'
    add_lookup Country, 'BLZ', value: 'BELIZE'
    add_lookup Country, 'BEN', value: 'BENIN'
    add_lookup Country, 'BMU', value: 'BERMUDA'
    add_lookup Country, 'BTN', value: 'BHUTAN'
    add_lookup Country, 'BOL', value: 'BOLIVIA'
    add_lookup Country, 'BES', value: 'BONAIRE, SINT EUSTATIUS AND SABA'
    add_lookup Country, 'BIH', value: 'BOSNIA AND HERZEGOVINA'
    add_lookup Country, 'BWA', value: 'BOTSWANA'
    add_lookup Country, 'BVT', value: 'BOUVET ISLAND'
    add_lookup Country, 'BRA', value: 'BRAZIL'
    add_lookup Country, 'IOT', value: 'BRITISH INDIAN OCEAN TERRITORY'
    add_lookup Country, 'VGB', value: 'BRITISH VIRGIN ISLANDS'
    add_lookup Country, 'BRN', value: 'BRUNEI'
    add_lookup Country, 'BGR', value: 'BULGARIA'
    add_lookup Country, 'BFA', value: 'BURKINA FASO'
    add_lookup Country, 'MMR', value: 'BURMA'
    add_lookup Country, 'BDI', value: 'BURUNDI'
    add_lookup Country, 'KHM', value: 'CAMBODIA'
    add_lookup Country, 'CMR', value: 'CAMEROON'
    add_lookup Country, 'CAN', value: 'CANADA'
    add_lookup Country, 'CPV', value: 'CAPE VERDE'
    add_lookup Country, 'CYM', value: 'CAYMAN ISLANDS'
    add_lookup Country, 'CAF', value: 'CENTRAL AFRICAN REPUBLIC'
    add_lookup Country, 'TCD', value: 'CHAD'
    add_lookup Country, 'XLC', value: 'CHANNEL ISLANDS NOT JERSEY OR GUERNSEY'
    add_lookup Country, 'CHL', value: 'CHILE'
    add_lookup Country, 'CHN', value: 'CHINA'
    add_lookup Country, 'CXR', value: 'CHRISTMAS ISLAND'
    add_lookup Country, 'CCK', value: 'COCOS (KEELING) ISLANDS'
    add_lookup Country, 'COL', value: 'COLOMBIA'
    add_lookup Country, 'COM', value: 'COMOROS'
    add_lookup Country, 'COG', value: 'CONGO'
    add_lookup Country, 'COD', value: 'CONGO (DEMOCRATIC REPUBLIC)'
    add_lookup Country, 'COK', value: 'COOK ISLANDS'
    add_lookup Country, 'CRI', value: 'COSTA RICA'
    add_lookup Country, 'HRV', value: 'CROATIA'
    add_lookup Country, 'CUB', value: 'CUBA'
    add_lookup Country, 'CUW', value: 'CURAÇAO'
    add_lookup Country, 'XAE', value: 'CYPRUS (EUROPEAN UNION)'
    add_lookup Country, 'XBN', value: 'CYPRUS (NON-EUROPEAN UNION)'
    add_lookup Country, 'CZE', value: 'CZECH REPUBLIC'
    add_lookup Country, 'DNK', value: 'DENMARK'
    add_lookup Country, 'DJI', value: 'DJIBOUTI'
    add_lookup Country, 'DMA', value: 'DOMINICA'
    add_lookup Country, 'DOM', value: 'DOMINICAN REPUBLIC'
    add_lookup Country, 'TLS', value: 'EAST TIMOR'
    add_lookup Country, 'ECU', value: 'ECUADOR'
    add_lookup Country, 'EGY', value: 'EGYPT'
    add_lookup Country, 'SLV', value: 'EL SALVADOR'
    add_lookup Country, 'GNQ', value: 'EQUATORIAL GUINEA'
    add_lookup Country, 'ERI', value: 'ERITREA'
    add_lookup Country, 'EST', value: 'ESTONIA'
    add_lookup Country, 'SWZ', value: 'ESWATINI'
    add_lookup Country, 'ETH', value: 'ETHIOPIA'
    add_lookup Country, 'FLK', value: 'FALKLAND ISLANDS'
    add_lookup Country, 'FRO', value: 'FAROE ISLANDS'
    add_lookup Country, 'FJI', value: 'FIJI'
    add_lookup Country, 'FIN', value: 'FINLAND'
    add_lookup Country, 'FRA', value: 'FRANCE'
    add_lookup Country, 'GUF', value: 'FRENCH GUIANA'
    add_lookup Country, 'PYF', value: 'FRENCH POLYNESIA'
    add_lookup Country, 'ATF', value: 'FRENCH SOUTHERN TERRITORIES'
    add_lookup Country, 'GAB', value: 'GABON'
    add_lookup Country, 'GMB', value: 'GAMBIA, THE'
    add_lookup Country, 'GEO', value: 'GEORGIA'
    add_lookup Country, 'DEU', value: 'GERMANY'
    add_lookup Country, 'GHA', value: 'GHANA'
    add_lookup Country, 'GIB', value: 'GIBRALTAR'
    add_lookup Country, 'GRC', value: 'GREECE'
    add_lookup Country, 'GRL', value: 'GREENLAND'
    add_lookup Country, 'GRD', value: 'GRENADA'
    add_lookup Country, 'GLP', value: 'GUADELOUPE'
    add_lookup Country, 'GUM', value: 'GUAM'
    add_lookup Country, 'GTM', value: 'GUATEMALA'
    add_lookup Country, 'GIN', value: 'GUINEA'
    add_lookup Country, 'GNB', value: 'GUINEA-BISSAU'
    add_lookup Country, 'GUY', value: 'GUYANA'
    add_lookup Country, 'HTI', value: 'HAITI'
    add_lookup Country, 'HMD', value: 'HEARD ISLAND AND MCDONALD ISLANDS'
    add_lookup Country, 'HND', value: 'HONDURAS'
    add_lookup Country, 'HKG', value: 'HONG KONG (SPECIAL ADMINISTRATIVE REGION OF CHINA)'
    add_lookup Country, 'HUN', value: 'HUNGARY'
    add_lookup Country, 'ISL', value: 'ICELAND'
    add_lookup Country, 'IND', value: 'INDIA'
    add_lookup Country, 'IDN', value: 'INDONESIA'
    add_lookup Country, 'IRN', value: 'IRAN'
    add_lookup Country, 'IRQ', value: 'IRAQ'
    add_lookup Country, 'IRL', value: 'IRELAND'
    add_lookup Country, 'IMN', value: 'ISLE OF MAN'
    add_lookup Country, 'ISR', value: 'ISRAEL'
    add_lookup Country, 'ITA', value: 'ITALY'
    add_lookup Country, 'CIV', value: 'IVORY COAST'
    add_lookup Country, 'JAM', value: 'JAMAICA'
    add_lookup Country, 'JPN', value: 'JAPAN'
    add_lookup Country, 'JOR', value: 'JORDAN'
    add_lookup Country, 'KAZ', value: 'KAZAKHSTAN'
    add_lookup Country, 'KEN', value: 'KENYA'
    add_lookup Country, 'KIR', value: 'KIRIBATI'
    add_lookup Country, 'PRK', value: 'KOREA (NORTH)'
    add_lookup Country, 'KOR', value: 'KOREA (SOUTH)'
    add_lookup Country, 'QOK', value: 'KOSOVO'
    add_lookup Country, 'KWT', value: 'KUWAIT'
    add_lookup Country, 'KGZ', value: 'KYRGYZSTAN'
    add_lookup Country, 'LAO', value: 'LAOS'
    add_lookup Country, 'LVA', value: 'LATVIA'
    add_lookup Country, 'LBN', value: 'LEBANON'
    add_lookup Country, 'LSO', value: 'LESOTHO'
    add_lookup Country, 'LBR', value: 'LIBERIA'
    add_lookup Country, 'LBY', value: 'LIBYA'
    add_lookup Country, 'LIE', value: 'LIECHTENSTEIN'
    add_lookup Country, 'LTU', value: 'LITHUANIA'
    add_lookup Country, 'LUX', value: 'LUXEMBOURG'
    add_lookup Country, 'MAC', value: 'MACAO (SPECIAL ADMINISTRATIVE REGION OF CHIINA)'
    add_lookup Country, 'MKD', value: 'MACEDONIA'
    add_lookup Country, 'MDG', value: 'MADAGASCAR'
    add_lookup Country, 'MWI', value: 'MALAWI'
    add_lookup Country, 'MYS', value: 'MALAYSIA'
    add_lookup Country, 'MDV', value: 'MALDIVES'
    add_lookup Country, 'MLI', value: 'MALI'
    add_lookup Country, 'MLT', value: 'MALTA'
    add_lookup Country, 'MHL', value: 'MARSHALL ISLANDS'
    add_lookup Country, 'MTQ', value: 'MARTINIQUE'
    add_lookup Country, 'MRT', value: 'MAURITANIA'
    add_lookup Country, 'MUS', value: 'MAURITIUS'
    add_lookup Country, 'MYT', value: 'MAYOTTE'
    add_lookup Country, 'MEX', value: 'MEXICO'
    add_lookup Country, 'FSM', value: 'MICRONESIA'
    add_lookup Country, 'MDA', value: 'MOLDOVA'
    add_lookup Country, 'MCO', value: 'MONACO'
    add_lookup Country, 'MNG', value: 'MONGOLIA'
    add_lookup Country, 'MNE', value: 'MONTENEGRO'
    add_lookup Country, 'MSR', value: 'MONTSERRAT'
    add_lookup Country, 'MAR', value: 'MOROCCO'
    add_lookup Country, 'MOZ', value: 'MOZAMBIQUE'
    add_lookup Country, 'NAM', value: 'NAMIBIA'
    add_lookup Country, 'NRU', value: 'NAURU'
    add_lookup Country, 'NPL', value: 'NEPAL'
    add_lookup Country, 'NLD', value: 'NETHERLANDS'
    add_lookup Country, 'NCL', value: 'NEW CALEDONIA'
    add_lookup Country, 'NZL', value: 'NEW ZEALAND'
    add_lookup Country, 'NIC', value: 'NICARAGUA'
    add_lookup Country, 'NER', value: 'NIGER'
    add_lookup Country, 'NGA', value: 'NIGERIA'
    add_lookup Country, 'NIU', value: 'NIUE'
    add_lookup Country, 'NFK', value: 'NORFOLK ISLAND'
    add_lookup Country, 'MNP', value: 'NORTHERN MARIANA ISLANDS'
    add_lookup Country, 'NOR', value: 'NORWAY'
    add_lookup Country, 'PSE', value: 'OCCUPIED PALESTINIAN TERRITORIES'
    add_lookup Country, 'OMN', value: 'OMAN'
    add_lookup Country, 'PAK', value: 'PAKISTAN'
    add_lookup Country, 'PLW', value: 'PALAU'
    add_lookup Country, 'PAN', value: 'PANAMA'
    add_lookup Country, 'PNG', value: 'PAPUA NEW GUINEA'
    add_lookup Country, 'PRY', value: 'PARAGUAY'
    add_lookup Country, 'PER', value: 'PERU'
    add_lookup Country, 'PHL', value: 'PHILIPPINES'
    add_lookup Country, 'PCN', value: 'PITCAIRN, HENDERSON, DUCIE AND OENO ISLANDS'
    add_lookup Country, 'POL', value: 'POLAND'
    add_lookup Country, 'PRT', value: 'PORTUGAL'
    add_lookup Country, 'PRI', value: 'PUERTO RICO'
    add_lookup Country, 'QAT', value: 'QATAR'
    add_lookup Country, 'REU', value: 'RÉUNION'
    add_lookup Country, 'ROU', value: 'ROMANIA'
    add_lookup Country, 'RUS', value: 'RUSSIA'
    add_lookup Country, 'RWA', value: 'RWANDA'
    add_lookup Country, 'MAF', value: 'SAINT MARTIN (FRENCH PART)'
    add_lookup Country, 'WSM', value: 'SAMOA'
    add_lookup Country, 'SMR', value: 'SAN MARINO'
    add_lookup Country, 'STP', value: 'SAO TOME AND PRINCIPE'
    add_lookup Country, 'SAU', value: 'SAUDI ARABIA'
    add_lookup Country, 'SEN', value: 'SENEGAL'
    add_lookup Country, 'SRB', value: 'SERBIA'
    add_lookup Country, 'SYC', value: 'SEYCHELLES'
    add_lookup Country, 'SLE', value: 'SIERRA LEONE'
    add_lookup Country, 'SGP', value: 'SINGAPORE'
    add_lookup Country, 'SXM', value: 'SINT MAARTEN (DUTCH PART)'
    add_lookup Country, 'SVK', value: 'SLOVAKIA'
    add_lookup Country, 'SVN', value: 'SLOVENIA'
    add_lookup Country, 'SLB', value: 'SOLOMON ISLANDS'
    add_lookup Country, 'SOM', value: 'SOMALIA'
    add_lookup Country, 'ZAF', value: 'SOUTH AFRICA'
    add_lookup Country, 'SGS', value: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'
    add_lookup Country, 'SSD', value: 'SOUTH SUDAN'
    add_lookup Country, 'XDE', value: 'SPAIN (EXCEPT CANARY ISLANDS)'
    add_lookup Country, 'LKA', value: 'SRI LANKA'
    add_lookup Country, 'BLM', value: 'ST BARTHÉLEMY'
    add_lookup Country, 'SHN', value: 'ST HELENA, ASCENSION AND TRISTAN DA CUNHA'
    add_lookup Country, 'KNA', value: 'ST KITTS AND NEVIS'
    add_lookup Country, 'LCA', value: 'ST LUCIA'
    add_lookup Country, 'SPM', value: 'ST PIERRE AND MIQUELON'
    add_lookup Country, 'VCT', value: 'ST VINCENT AND THE GRENADINES'
    add_lookup Country, 'SDN', value: 'SUDAN'
    add_lookup Country, 'SUR', value: 'SURINAME'
    add_lookup Country, 'SJM', value: 'SVALBARD AND JAN MAYEN'
    add_lookup Country, 'SWE', value: 'SWEDEN'
    add_lookup Country, 'CHE', value: 'SWITZERLAND'
    add_lookup Country, 'SYR', value: 'SYRIA'
    add_lookup Country, 'TWN', value: 'TAIWAN'
    add_lookup Country, 'TJK', value: 'TAJIKISTAN'
    add_lookup Country, 'TZA', value: 'TANZANIA'
    add_lookup Country, 'THA', value: 'THAILAND'
    add_lookup Country, 'TGO', value: 'TOGO'
    add_lookup Country, 'TKL', value: 'TOKELAU'
    add_lookup Country, 'TON', value: 'TONGA'
    add_lookup Country, 'TTO', value: 'TRINIDAD AND TOBAGO'
    add_lookup Country, 'TUN', value: 'TUNISIA'
    add_lookup Country, 'TUR', value: 'TURKEY'
    add_lookup Country, 'TKM', value: 'TURKMENISTAN'
    add_lookup Country, 'TCA', value: 'TURKS AND CAICOS ISLANDS'
    add_lookup Country, 'TUV', value: 'TUVALU'
    add_lookup Country, 'UGA', value: 'UGANDA'
    add_lookup Country, 'UKR', value: 'UKRAINE'
    add_lookup Country, 'ARE', value: 'UNITED ARAB EMIRATES'
    add_lookup Country, 'XKU', value: 'UNITED KINGDOM ⁯'
    add_lookup Country, 'USA', value: 'UNITED STATES'
    add_lookup Country, 'UMI', value: 'UNITED STATES MINOR OUTLYING ISLANDS'
    add_lookup Country, 'VIR', value: 'UNITED STATES VIRGIN ISLANDS'
    add_lookup Country, 'URY', value: 'URUGUAY'
    add_lookup Country, 'UZB', value: 'UZBEKISTAN'
    add_lookup Country, 'VUT', value: 'VANUATU'
    add_lookup Country, 'VAT', value: 'VATICAN CITY'
    add_lookup Country, 'VEN', value: 'VENEZUELA'
    add_lookup Country, 'VNM', value: 'VIETNAM'
    add_lookup Country, 'WLF', value: 'WALLIS AND FUTUNA'
    add_lookup Country, 'ESH', value: 'WESTERN SAHARA'
    add_lookup Country, 'YEM', value: 'YEMEN'
    add_lookup Country, 'ZMB', value: 'ZAMBIA'
    add_lookup Country, 'ZWE', value: 'ZIMBABWE'
  end
end
