name: Build DMS Image
on:
  pull_request:
  # workflow_run:
  #   workflows: ["Test"]
  #   types:
  #     - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    defaults:
      run:
        working-directory: build/dms-app/
    env:
      AWS_DEFAULT_REGION: eu-west-2
      ACCOUNT_ID: 930039174803
      SECURITY_GROUP: sg-042167d079bf0335f
      SECURITY_GROUP_RULE: sgr-0787cf5e2a3ba295c

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: git branch
      - run: env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::930039174803:role/dms-github-actions-deploy-role
          role-session-name: configurerole
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: Zip artifacts
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "mbis_app.zip"

      - name: Upload to AWS S3
        run: |
          echo "Uploading artifacts to $env.PROFILE environment."
          aws s3 cp ../../mbis_app.zip s3://ndrs-mbis-eu-west-2-930039174803-state-bucket/

      # - name: Update Security Ingress for Packer github
      #   run: |
      #     curl -s "https://checkip.amazonaws.com" | xargs -I % sh -c 'aws ec2 modify-security-group-rules --group-id ${{env.SECURITY_GROUP}} --security-group-rules "SecurityGroupRuleId=${{env.SECURITY_GROUP_RULE}},SecurityGroupRule={Description='Security',IpProtocol=tcp,CidrIpv4=%/32,FromPort=22,ToPort=22}"'
      
      # - name: Get Latest Base Image ID 
      #   id: base_image_id
      #   run: |
      #     aws s3 cp s3://ndrs-dms-pipeline-archivefiles/dev/BASEIMAGE_AMI_ID BASEIMAGE_AMI_ID
      #     aws s3 cp s3://ndrs-dms-pipeline-archivefiles/dev/CURRENT_COMMIT_ID CURRENT_COMMIT_ID
      #     BASEIMAGE_AMI_ID=$(cat BASEIMAGE_AMI_ID)
      #     CURRENT_COMMIT_ID=$(cat CURRENT_COMMIT_ID)
      #     echo "*************"
      #     echo $BASEIMAGE_AMI_ID
      #     echo $CURRENT_COMMIT_ID
      #     echo "*************"
      #     echo "base_image_id=$BASEIMAGE_AMI_ID" >> $GITHUB_OUTPUT
      #     echo "current_commit_id=$CURRENT_COMMIT_ID" >> $GITHUB_OUTPUT

      # - name: Setup `packer`
      #   uses: hashicorp/setup-packer@main
      #   id: setup

      # - name: Initialize Packer Template
      #   id: init
      #   run: "packer init ./dms-app.pkr.hcl"

      # - name: Validate Template
      #   id: validate
      #   run: "packer validate -syntax-only ./dms-app.pkr.hcl"

      # - name: Build Artifact
      #   id: build
      #   run: "packer build -color=false -on-error=abort -var 'base_image_id=${{ steps.base_image_id.outputs.base_image_id}}' -var 'commit_hash=${{ steps.base_image_id.outputs.current_commit_id}}' ./dms-app.pkr.hcl"