name: Lint

on: [pull_request]

jobs:
  rubocop:
    name: RuboCop

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch everything
    - name: Remove mini_racer CentOS 7 shim from Gemfile.lock
      run: sed -i.bak -e '/mini_racer (0.6.2-x86_64-linux)/,+1d' Gemfile.lock
    - name: Set up Ruby + Bundle
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run RuboCop against BASE..HEAD changes
      run: bundle exec rake rubocop:diff origin/${GITHUB_BASE_REF#*/}

